DROP SCHEMA IF EXISTS `aiom`;
CREATE SCHEMA IF NOT EXISTS `aiom` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

USE mysql;
DELETE FROM user WHERE User='aiom' AND Host='%';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON aiom.* TO 'aiom'@'%' IDENTIFIED BY 'aiom';